/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package HelpDesk;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Kevin
 */
public class LandingForm extends javax.swing.JFrame implements TreeSelectionListener {
    private URL helpURL;
    private static boolean DEBUG = false;
    
    /**
     * Creates new form LandingForm
     */
    public LandingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        DefaultMutableTreeNode top =
        new DefaultMutableTreeNode("HelpDesk");
        createNodes(top);
        tree = new javax.swing.JTree(top);
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ThreadIDTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JToggleButton();
        ReplyButton = new javax.swing.JButton();
        htmlView = new javax.swing.JScrollPane();
        htmlPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.addTreeSelectionListener(this);
        jScrollPane.setViewportView(tree);

        ExitButton.setText("Sign Off");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Find Thread by Thread ID:");

        jLabel2.setText("Thread ID:");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ReplyButton.setText("Reply");
        ReplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplyButtonActionPerformed(evt);
            }
        });

        htmlPane.setEditable(false);
        initHelp();
        htmlPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        htmlView.setViewportView(htmlPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                        .addComponent(ReplyButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ThreadIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SearchButton))
                        .addComponent(jScrollPane)
                        .addComponent(htmlView, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitButton)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(htmlView, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ThreadIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton)))
                    .addComponent(ReplyButton))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void valueChanged(TreeSelectionEvent e) {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                           tree.getLastSelectedPathComponent();

        if (node == null) return;

        Object nodeInfo = node.getUserObject();
        if (node.isLeaf()) {
            BookInfo book = (BookInfo)nodeInfo;
            displayURL(book.bookURL);
            if (DEBUG) {
                System.out.print(book.bookURL + ":  \n    ");
            }
        } else {
            displayURL(helpURL); 
        }
        if (DEBUG) {
            System.out.println(nodeInfo.toString());
        }
    }
    
    private class BookInfo {
        public String bookName;
        public URL bookURL;
        
        public BookInfo(String book, String filename) {
            bookName = book;
            bookURL = getClass().getResource(filename);
            if (bookURL == null) {
                System.err.println("Couldn't find file: "
                                   + filename);
            }
        }

        public String toString() {
            return bookName;
        }
    }
    
    private void initHelp() {
        String s = "Welcome.txt";
        helpURL = getClass().getResource(s);
        if (helpURL == null) {
            System.err.println("Couldn't open help file: " + s);
        } else if (DEBUG) {
            System.out.println("Help URL is " + helpURL);
        }

        displayURL(helpURL);
    }
    
    private void displayURL(URL url) {
        try {
            if (url != null) {
                htmlPane.setPage(url);
            } else { //null url
		htmlPane.setText("File Not Found");
                if (DEBUG) {
                    System.out.println("Attempted to display a null URL.");
                }
            }
        } catch (IOException e) {
            System.err.println("Attempted to read a bad URL: " + url);
        }
    }
    
    private void createNodes(DefaultMutableTreeNode top) {
        DefaultMutableTreeNode category = null;
        DefaultMutableTreeNode category2 = null;
        DefaultMutableTreeNode category3 = null;
        DefaultMutableTreeNode file = null;

        String test[] = {"General Forums", "Announcements"};
        
        category = new DefaultMutableTreeNode("General Forums");
        top.add(category);
        
        DatabaseConnection dbConnect = new DatabaseConnection();
        Connection conn = dbConnect.connectToDB();
        
        // Query for total Forum topics
        String sql = "SELECT * FROM `ForumCategories`"; // WHERE Username = '"+userName+"'"; 
        ResultSet rs = dbConnect.getResults(conn, sql);
        int parentID = 0;
        try {
            while (rs.next())
            {
                category2 = new DefaultMutableTreeNode(rs.getString("Name"));
                category.add(category2);
                
                parentID = rs.getInt("ForumCategoryID");
                String subSQL = "SELECT * FROM `ForumSubCategories` WHERE ParentID = '"+parentID+"'"; 
                ResultSet subRS = dbConnect.getResults(conn, subSQL);
                while (subRS.next())
                {
                    category3 = new DefaultMutableTreeNode(subRS.getString("Name"));
                    category2.add(category3);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(HelpDeskMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
        /*category2 = new DefaultMutableTreeNode("Announcements");
        category.add(category2);    

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("Announcements - ReadMe",
                                        "AnnouncementsInfo.txt"));
        category2.add(file);*/

        file = new DefaultMutableTreeNode(new BookInfo
                                        ("Try not to use Too Many Characters!",
                                        "MessageFromWorldsMostAnnoyingForumMod.txt"));
        category2.add(file);

        /*category2 = new DefaultMutableTreeNode("Queries");
        category.add(category2);

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("Queries - ReadMe",
                                        "QueriesInfo.txt"));
        category.add(file);*/

        /*category3 = new DefaultMutableTreeNode("Math");
        category2.add(category3);

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("Pythagorean Theorem",
                                        "PythagoreanTheorem.txt"));
        category3.add(file);*/

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("Jacobian Matrix?",
                                        "JacobianMatrix.txt"));
        category3.add(file);*/

       /* category3 = new DefaultMutableTreeNode("Science");
        category2.add(category3);

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("Newton's Laws of Motion?",
                                        "NewtonLawofMotion.txt"));
        category3.add(file);*/

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("Peroxide Formation - Ethers?",
                                        "PeroxideFormation.txt"));
        category3.add(file);*/

        /*category3 = new DefaultMutableTreeNode("English");
        category2.add(category3);

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("What's the Meaning of Life?",
                                        "MeaningofLife.txt"));
        category3.add(file);*/

        /*category3 = new DefaultMutableTreeNode("History");
        category2.add(category3);

        /*file = new DefaultMutableTreeNode(new BookInfo
                                        ("Treaty of Paris (1783) Repercussions",
                                        "TreatyofParis.txt"));
        category3.add(file);*/

    }
    
    
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Cannot find specified thread with ThreadID: '" + ThreadIDTextField.getText() + "'");
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ReplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplyButtonActionPerformed
        // TODO add your handling code here:
        
        
        ReplyForm replyForm1 = new ReplyForm();
        replyForm1.setVisible(true);
        
    }//GEN-LAST:event_ReplyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LandingForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ReplyButton;
    private javax.swing.JToggleButton SearchButton;
    private javax.swing.JTextField ThreadIDTextField;
    private javax.swing.JEditorPane htmlPane;
    private javax.swing.JScrollPane htmlView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
