/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package HelpDesk;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Kevin
 */
public class ReplyForm extends javax.swing.JFrame {
    private int bookType;
    private int userID;
    private String subCat;
    private int parentComment;
    private int userType;
    /**
     * Creates new form ReplyForm
     */
    public ReplyForm(int bookType, int userID, String subCat, int parentComment, int userType) {
        this.bookType = bookType;
        this.userID = userID;
        this.subCat = subCat;
        this.parentComment = parentComment;
        this.userType = userType;
        initComponents();
        OriginalComment(parentComment);
    }
    public ReplyForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ParentCommentTextArea = new javax.swing.JTextArea();
        ExitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        SubmitButton = new javax.swing.JButton();
        VisibleToPublicCheckbox = new javax.swing.JCheckBox();
        QuestionTitleLabel = new javax.swing.JLabel();
        QuestionTitleTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ParentCommentTextArea.setColumns(20);
        ParentCommentTextArea.setEditable(false);
        ParentCommentTextArea.setRows(5);
        jScrollPane1.setViewportView(ParentCommentTextArea);

        ExitButton.setText("Cancel");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        contentTextArea.setColumns(20);
        contentTextArea.setRows(5);
        jScrollPane2.setViewportView(contentTextArea);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        VisibleToPublicCheckbox.setSelected(true);
        VisibleToPublicCheckbox.setText("Visible to Public");

        if(bookType != 0)  {      QuestionTitleLabel.setVisible(false);  }
        QuestionTitleLabel.setText("Question Title");

        if(bookType != 0)  {      QuestionTitleTextField.setVisible(false);  }
        QuestionTitleTextField.setText("Insert Title Here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SubmitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VisibleToPublicCheckbox)
                        .addGap(138, 138, 138)
                        .addComponent(QuestionTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuestionTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitButton)
                            .addComponent(VisibleToPublicCheckbox))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuestionTitleLabel)
                            .addComponent(QuestionTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LandingForm(userType, userID).setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        DatabaseConnection db = new DatabaseConnection();
        Connection conn = db.connectToDB();
        String sql = "";
        
        if(bookType == 0)
        {
            //This is someone submitting a question to a subCategory
            sql = "INSERT INTO  `lepolted`.`ForumQuestions` ("
                    +"`QuestionTitle` ,"
                    +"`Question` ,"
                    +"`QuestionID` ,"
                    +"`SubCategoryID`"
                    +")"
                    +"VALUES ("
                    +"'"+ QuestionTitleTextField.getText() +"', "
                    +"'"+ contentTextArea.getText() +"', "
                    +"NULL ,"
                    +"'"+ HelpFunctions.subCat(subCat) + "'"
                    +")";
            
        }
        else if(bookType == 1)
        {
            //This is someone Answering a question
            sql = "INSERT INTO  `lepolted`.`ForumComments` ("
                    +"`QuestionID` ,"
                    +"`CommentID` ,"
                    +"`ReplyID` ,"
                    +"`Comment` ,"
                    +"`Author`"
                    +")"
                    +"VALUES ("
                    +"'"+ parentComment +"', "
                    +"NULL, "
                    +"NULL ,"
                    +"'"+ contentTextArea.getText() + "', "
                    +"'"+ userID + "'"
                    +")";
        }
        else
        {
            //This is someone commenting
            sql = "INSERT INTO  `lepolted`.`ForumComments` ("
                    +"`QuestionID` ,"
                    +"`CommentID` ,"
                    +"`ReplyID` ,"
                    +"`Comment` ,"
                    +"`Author`"
                    +")"
                    +"VALUES ("
                    +"NULL, "
                    +"NULL, "
                    +"'"+ parentComment + "', "
                    +"'"+ contentTextArea.getText() + "', "
                    +"'"+ userID + "'"
                    +")";
        }
        
        //Update Database and return to main form.
        db.updateDatabase(conn, sql);
        this.dispose();
        new LandingForm(userType,userID).setVisible(true);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReplyForm().setVisible(true);
            }
        });
    }
    
    String OriginalComment(int commentID)
    {
        String comment ="";
        DatabaseConnection db = new DatabaseConnection();
        Connection conn = db.connectToDB();
        String sql = "Select * from ";
        if(bookType == 0)
        {
            ParentCommentTextArea.setText("Insert question below");
        }
        else if(bookType == 1)
        {
            //This is someone replying to an answer to a question
            sql += "`ForumQuestions` where QuestionID = '"+commentID+"'";
            ResultSet rs = db.getResults(conn, sql);
            try {
                if(rs.next())
                {
                    ParentCommentTextArea.setText(rs.getString("Question"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(ReplyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            //This is someone commenting
            sql += "`ForumComments` where CommentID = '"+commentID+"'";
                ResultSet rs = db.getResults(conn, sql);
            try {
                if(rs.next())
                {
                    ParentCommentTextArea.setText(rs.getString("Comment"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(ReplyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        return comment;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextArea ParentCommentTextArea;
    private javax.swing.JLabel QuestionTitleLabel;
    private javax.swing.JTextField QuestionTitleTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JCheckBox VisibleToPublicCheckbox;
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
